[[redirects]]
  from = "/"
  to = "/en/"
  status = 302
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"]}

[[redirects]]
  from = "/"
  to = "/ru/"
  status = 302
  force = false
  query = {path = ":path"}
  conditions = {Language = ["ru"]}

[[redirects]]
  from = "/"
  to = "/en/"


[[redirects]]
  from = "https://jediyozh.com"
  to = "https://jediyozh.com/en"
