name: Lighthouse CI
on: push
jobs:
  static-dist-dir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Build
        run: |
          npm install
          npm run build
      - uses: actions/checkout@v2
      - name: Run Lighthouse against a static dist dir
        uses: treosh/lighthouse-ci-action@v3
        with:
          configPath: ./lighthouserc.json
          budgetPath: ./budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true
