name: Prettier

on: push

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: creyD/prettier_action@v3.0
        with:
          prettier_options: --write "./src/**/*.{html,css,js}"
